name: Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.md'
      - '.markdownlint-cli2.yaml'
      - '.github/workflows/lint.yml' # This workflow

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: "Check Markdown documents"
        uses: DavidAnson/markdownlint-cli2-action@v19
