name: Spellcheck

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.md'
      - '.spellcheck*'
      - '.github/workflows/spellcheck.yaml' # This workflow file

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Python 3.12'
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: 'Create venv'
        run: |
          python3 -m venv --upgrade-deps venv

      - name: 'Install pyspelling and aspell'
        run: |
          sudo sudo apt-get update
          sudo apt-get install -y aspell aspell-en
          source venv/bin/activate
          python3 -m pip install 'pyspelling'

      - name: 'Check spelling'
        run: |
          source venv/bin/activate
          python3 -m pyspelling --config .spellcheck.yml --spellchecker aspell
